#!/usr/bin/env bash

echo "==== delete bucket."

# Check if there is 1 argument provided
if [ -z "$1" ]; then
    echo "No input argument provided!! The arg should be 'my-bucket-name'"
    exit 1
fi

BUCKET_NAME="$1"

aws s3api delete-bucket \
    --bucket "$BUCKET_NAME"